<a href="https://colab.research.google.com/github/AliceYuan01/PyTorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.







In [1]:
import torch
import numpy as np

# **LISTS**


In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [3]:
np1 = np.random.rand(3,4)
np1


array([[0.98221121, 0.67358965, 0.99708423, 0.05728511],
       [0.5692064 , 0.98155511, 0.52977484, 0.10624785],
       [0.83363037, 0.77246261, 0.14511538, 0.60415102]])

In [4]:
np1.dtype


dtype('float64')

# **TENSORS**

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 1.7858,  0.8184,  0.1900, -0.3514],
        [-0.3450, -0.8666,  0.4120, -0.2305],
        [ 0.5937, -0.1173, -0.3396,  0.2528]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9822, 0.6736, 0.9971, 0.0573],
        [0.5692, 0.9816, 0.5298, 0.1062],
        [0.8336, 0.7725, 0.1451, 0.6042]], dtype=torch.float64)